services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    container_name: keycloak
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "keycloak"
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    volumes:
      - ./realm-imports:/opt/keycloak/data/import:ro
      - ./customPolicy/target/CustomPolicy-1.0-SNAPSHOT.jar:/opt/keycloak/providers/CustomPolicy-1.0-SNAPSHOT.jar
    depends_on:
      postgres:
        condition: service_healthy

  maildev:
    container_name: maildev
    image: maildev/maildev:latest
    ports:
      - "1080:1080"
      - "1025:1025"
  postgres:
    container_name: postgres
    image: postgres:17.6-alpine
    command: postgres -c 'max_connections=300' -c 'shared_buffers=80MB'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U admin -d keycloak
      interval: 5s
      timeout: 3s
      retries: 10